"""Byte-level BPE tokenizer package (Phase 2).

tokenizer.json / config.json are generated by train_tokenizer.py and are
gitignored (see .gitignore) -- they are an artifact of running training on
a real corpus, not source code.
"""
